version: '3.3'

services:
  pb-app-nginx.docker:
    build:
      context: ./app
      dockerfile: Dockerfile.nginx.prod
    image: pb-app-nginx:1.13
    container_name: pb-app-nginx
    restart: always
    depends_on:
      - pb-app.docker
    ports:
      - 8080:8080
      - 8081:8081
      - 8082:8082
    volumes:
      - ./app/storage/:/app/storage/

  pb-app.docker:
    build:
      context: ./app
      dockerfile: Dockerfile.php.prod
    image: pb-app-php:7.2-fpm
    container_name: pb-app
    restart: always
    depends_on:
      - pb-prerender.docker
      - pb-redis.docker
    volumes:
      - ./app/storage/:/app/storage/

  pb-prerender.docker:
    build:
      context: ./prerender
      dockerfile: Dockerfile.prod
    image: pb-prerender-node:10
    container_name: pb-prerender
    restart: always

  pb-redis.docker:
    image: redis:3.2
    container_name: pb-redis
    restart: always
