version: '3.3'

services:
  pb-nginx.docker:
    image: nginx:1.13
    container_name: pb-nginx
    restart: always
    depends_on:
      - pb-app.docker
    ports:
      - 8080:8080
      - 8081:8081
      - 8082:8082
    volumes:
      - ./app/:/app/
      - ./docker/config/nginx/sites/:/etc/nginx/conf.d/

  pb-app.docker:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    image: pb-app-php:7.2-fpm
    container_name: pb-app
    restart: always
    depends_on:
      - pb-renderer.docker
      - pb-mysql.docker
      - pb-redis.docker
      - pb-maildev.docker
    volumes:
      - ./app/:/app/
      - ./app/docker/php.dev.ini:/usr/local/etc/php/php.ini

  pb-renderer.docker:
    build:
      context: ./renderer
      dockerfile: Dockerfile.prod
    image: pb-renderer-node:10
    container_name: pb-renderer
    restart: always
    ports:
      - 3000:3000

  pb-mysql.docker:
    image: mysql:5.7
    container_name: pb-mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'photo_blog'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'dev'
      MYSQL_PASSWORD: 'dev'
    ports:
      - 3306:3306
    volumes:
      - ./docker/storage/mysql/var/lib/mysql:/var/lib/mysql
      - ./docker/config/mysql/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
      - ./docker/config/mysql/my.cnf:/etc/mysql/my.cnf

  pb-redis.docker:
    image: redis:3.2
    container_name: pb-redis
    restart: always

  pb-maildev.docker:
    image: djfarrelly/maildev
    container_name: pb-maildev
    restart: always
    ports:
      - 8083:80
