version: '3.3'

services:

  pb-app.docker:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    image: pb-app-php:7.2-fpm
    container_name: pb-app
    restart: always
    ports:
      - 9000:9000
    depends_on:
      - pb-renderer.docker
      - pb-redis.docker
    volumes:
      - ./app/storage/:/app/storage/
      - ./app/docker/php.prod.ini:/usr/local/etc/php/php.ini

  pb-renderer.docker:
    build:
      context: ./renderer
      dockerfile: Dockerfile.prod
    image: pb-renderer-node:10
    container_name: pb-renderer
    restart: always

  pb-redis.docker:
    image: redis:3.2
    container_name: pb-redis
    restart: always
