version: '3.3'

services:
  pb-nginx.docker:
    build:
      context: ./app
      dockerfile: Dockerfile.nginx.prod
    image: pb-nginx:1.13
    container_name: pb-nginx
    restart: always
    depends_on:
      - pb-app.docker
    ports:
      - 8080:8080
      - 8081:8081
      - 8082:8082
    volumes:
      - ./app/storage/:/app/storage/

  pb-app.docker:
    build:
      context: ./app
      dockerfile: Dockerfile.php.prod
    image: pb-app-php:7.2-fpm
    container_name: pb-app
    restart: always
    ports:
      - 9000:9000
    depends_on:
      - pb-renderer.docker
      - pb-redis.docker
    volumes:
      - ./app/storage/:/app/storage/
      - ./app/docker/config/php/php.prod.ini:/usr/local/etc/php/php.ini

  pb-renderer.docker:
    build:
      context: ./renderer
      dockerfile: Dockerfile.prod
    image: pb-renderer-node:10
    container_name: pb-renderer
    restart: always

  pb-redis.docker:
    image: redis:3.2
    container_name: pb-redis
    restart: always
